version: '3.7'
services:
  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatbot
