apiVersion: apps/v1
kind: Deployment
metadata:
  name: manik-flask-gpt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: manik-flask-gpt
  template:
    metadata:
      labels:
        app: manik-flask-gpt
    spec:
      containers:
      - name: manik-flask-gpt
        image: 823711539498.dkr.ecr.us-east-1.amazonaws.com/manik-gpt:3.6
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-api
              key: key
